gcc16 merge

diff --git a/gcc/config-ml.in b/gcc/config-ml.in
--- a/gcc/config-ml.in
+++ b/gcc/config-ml.in
@@ -24,8 +24,8 @@
 # configuration script generated by Autoconf, you may include it under
 # the same distribution terms that you use for the rest of that program.
 #
-# Please report bugs to <gcc-bugs@gnu.org>
-# and send patches to <gcc-patches@gnu.org>.
+# Please report bugs according to <https://gcc.gnu.org/bugs/>
+# and send patches to <gcc-patches@gcc.gnu.org>.
 
 # It is advisable to support a few --enable/--disable options to let the
 # user select which libraries s/he really wants.
@@ -488,6 +488,23 @@ powerpc*-*-* | rs6000*-*-*)
 	;;
 esac
 
+# Use a filtered multilib list if requested.
+
+if [ x$with_multi_buildlist != x ]; then
+  old_multidirs="${multidirs}"
+  if [ ! -f $with_multi_buildlist ]; then
+    echo "config-ml.in: Failed to find $with_multi_buildlist"
+    exit 1
+  fi
+  multidirs=""
+  for x in ${old_multidirs}; do
+    found=`grep "^${x}$" $with_multi_buildlist`
+    if [ -n "$found" ]; then
+      multidirs="${multidirs} ${x}"
+    fi
+  done
+fi
+
 # Remove extraneous blanks from multidirs.
 # Tests like `if [ -n "$multidirs" ]' require it.
 multidirs=`echo "$multidirs" | sed -e 's/^[ ][ ]*//' -e 's/[ ][ ]*$//' -e 's/[ ][ ]*/ /g'`
@@ -528,6 +545,7 @@ multi-do:
 				exec_prefix="$(exec_prefix)" \
 				GOCFLAGS="$(GOCFLAGS) $${flags}" \
 				GDCFLAGS="$(GDCFLAGS) $${flags}" \
+				A68FLAGS="$(A68FLAGS) $${flags}" \
 				CXXFLAGS="$(CXXFLAGS) $${flags}" \
 				LIBCFLAGS="$(LIBCFLAGS) $${flags}" \
 				LIBCXXFLAGS="$(LIBCXXFLAGS) $${flags}" \
@@ -596,7 +614,12 @@ else
 fi
 
 if [ -z "${with_multisubdir}" ]; then
-  ml_subdir=
+  ml_top_subdir=`${CC-gcc} --print-multi-directory 2>/dev/null`
+  if [ "$ml_top_subdir" = . ]; then
+    ml_subdir=
+  else
+    ml_subdir=/$ml_top_subdir
+  fi
   ml_builddotdot=
   : # ml_srcdotdot= # already set
 else
@@ -674,6 +697,11 @@ if [ -n "${multidirs}" ] && [ -z "${ml_norecursion}" ]; then
   cd ..
 
   for ml_dir in ${multidirs}; do
+
+    if [ "${ml_dir}" == "${ml_top_subdir}" ]; then
+      echo "Skipping configure in multilib subdir ${ml_dir}"
+      continue
+    fi
 
     if [ "${ml_verbose}" = --verbose ]; then
       echo "Running configure in multilib subdir ${ml_dir}"
@@ -759,7 +787,7 @@ if [ -n "${multidirs}" ] && [ -z "${ml_norecursion}" ]; then
         break
       fi
     done
-    ml_config_env='CC="${CC_}$flags" CXX="${CXX_}$flags" F77="${F77_}$flags" GFORTRAN="${GFORTRAN_}$flags" GOC="${GOC_}$flags" GDC="${GDC_}$flags"'
+    ml_config_env='CC="${CC_}$flags" CXX="${CXX_}$flags" F77="${F77_}$flags" GFORTRAN="${GFORTRAN_}$flags" GOC="${GOC_}$flags" GDC="${GDC_}$flags" A68="${A68_}$flags"'
 
     if [ "${with_target_subdir}" = "." ]; then
 	CC_=$CC' '
@@ -768,6 +796,7 @@ if [ -n "${multidirs}" ] && [ -z "${ml_norecursion}" ]; then
 	GFORTRAN_=$GFORTRAN' '
 	GOC_=$GOC' '
 	GDC_=$GDC' '
+	A68_=$A68' '
     else
 	# Create a regular expression that matches any string as long
 	# as ML_POPDIR.
@@ -854,6 +883,20 @@ if [ -n "${multidirs}" ] && [ -z "${ml_norecursion}" ]; then
 	    GDC_="${GDC_}${arg}${multi_osdir} ${arg} " ;;
 	  *)
 	    GDC_="${GDC_}${arg} " ;;
+	  esac
+	done
+
+	A68_=
+	for arg in ${A68}; do
+	  case $arg in
+	  -[BIL]"${ML_POPDIR}"/*)
+	    A68_="${A68_}"`echo "X${arg}" | sed -n "s/X\\(-[BIL]${popdir_rx}\\).*/\\1/p"`/${ml_dir}`echo "X${arg}" | sed -n "s/X-[BIL]${popdir_rx}\\(.*\\)/\\1/p"`' ' ;;
+	  "${ML_POPDIR}"/*)
+	    A68_="${A68_}"`echo "X${arg}" | sed -n "s/X\\(${popdir_rx}\\).*/\\1/p"`/${ml_dir}`echo "X${arg}" | sed -n "s/X${popdir_rx}\\(.*\\)/\\1/p"`' ' ;;
+	  -B*/lib/)
+	    A68_="${A68_}${arg}${multi_osdir} ${arg} " ;;
+	  *)
+	    A68_="${A68_}${arg} " ;;
 	  esac
 	done
 
diff --git a/gcc/gcc/c/Make-lang.in b/gcc/gcc/c/Make-lang.in
--- a/gcc/gcc/c/Make-lang.in
+++ b/gcc/gcc/c/Make-lang.in
@@ -1,5 +1,5 @@
 # Top level -*- makefile -*- fragment for GNU C - C language.
-# Copyright (C) 1994-2025 Free Software Foundation, Inc.
+# Copyright (C) 1994-2026 Free Software Foundation, Inc.
 
 #This file is part of GCC.
 
@@ -58,6 +58,7 @@ C_AND_OBJC_OBJS = attribs.o c/c-errors.o c/c-decl.o c/c-typeck.o \
 # Language-specific object files for C.
 C_OBJS = c/c-lang.o c-family/stub-objc.o $(C_AND_OBJC_OBJS)
 c_OBJS = $(C_OBJS) cc1-checksum.o c/gccspec.o
+c_FDAS = cc1.fda
 
 # Use strict warnings for this front end.
 c-warn = $(STRICT_WARN)
@@ -92,26 +93,32 @@ components_in_prev = "bfd opcodes binutils fixincludes gas gcc gmp mpfr mpc isl 
 components_in_prev_target = "libstdc++-v3 libsanitizer libvtv libgcc libbacktrace libphobos zlib libgomp libatomic"
 
 cc1.fda: create_fdas_for_cc1
-	$(PROFILE_MERGER) $(shell ls -ha cc1_*.fda) --output_file cc1.fda -gcov_version 2
+	$(PROFILE_MERGER) $(shell ls -ha cc1_*.fda) --output_file cc1.fda -gcov_version `../stage1-gcc/xgcc$(exeext) --print-autofdo-gcov-version`
 
 create_fdas_for_cc1: ../stage1-gcc/cc1$(exeext) ../prev-gcc/$(PERF_DATA)
 	for component_in_prev in "$(components_in_prev)"; do \
 	  perf_path=../prev-$$component_in_prev/$(PERF_DATA); \
-	  echo "Perf path:"; \
-	  echo $$perf_path; \
+	  echo "Perf path:" $$perf_path "..." `[ -f $$perf_path ] && echo exists || echo does not exist`; \
 	  if [ -f $$perf_path ]; then \
 	    profile_name=cc1_$$component_in_prev.fda; \
-	    $(CREATE_GCOV) -binary ../stage1-gcc/cc1$(exeext) -gcov $$profile_name -profile $$perf_path -gcov_version 2; \
+	    if [ "x`$(PERF) buildid-list -i $$perf_path | grep '/cc1$$' && echo yes`" != "x" ]; then \
+	      $(CREATE_GCOV) -binary ../stage1-gcc/cc1$(exeext) -gcov $$profile_name -profile $$perf_path -profiler $(AFDO_PROFILER) -gcov_version `../stage1-gcc/xgcc$(exeext) --print-autofdo-gcov-version` || exit 1; \
+	    else \
+	      echo "  warning: $$perf_path is missing cc1!"; \
+	    fi; \
 	  fi; \
 	done;
 
 	for component_in_prev_target in "$(components_in_prev_target)"; do \
 	  perf_path=../prev-$(TARGET_SUBDIR)/$$component_in_prev_target/$(PERF_DATA); \
-	  echo "Perf path:"; \
-	  echo $$perf_path; \
+	  echo "Perf path:" $$perf_path "..." `[ -f $$perf_path ] && echo exists || echo does not exist`; \
 	  if [ -f $$perf_path ]; then \
 	    profile_name=cc1_$$component_in_prev_target.fda; \
-	    $(CREATE_GCOV) -binary ../prev-gcc/cc1$(exeext) -gcov $$profile_name -profile $$perf_path -gcov_version 2; \
+	    if [ "x`$(PERF) buildid-list -i $$perf_path | grep '/cc1$$' && echo yes`" != "x" ]; then \
+	      $(CREATE_GCOV) -binary ../prev-gcc/cc1$(exeext) -gcov $$profile_name -profile $$perf_path -profiler $(AFDO_PROFILER) -gcov_version `../prev-gcc/xgcc$(exeext) --print-autofdo-gcov-version` || exit 1; \
+	    else \
+	      echo "  warning: $$perf_path is missing cc1!"; \
+	    fi; \
 	  fi; \
 	done;
 
diff --git a/gcc/gcc/lto/Make-lang.in b/gcc/gcc/lto/Make-lang.in
--- a/gcc/gcc/lto/Make-lang.in
+++ b/gcc/gcc/lto/Make-lang.in
@@ -1,5 +1,5 @@
 # Top level -*- makefile -*- fragment for LTO
-#   Copyright (C) 2009-2025 Free Software Foundation, Inc.
+#   Copyright (C) 2009-2026 Free Software Foundation, Inc.
 
 #This file is part of GCC.
 
@@ -26,18 +26,15 @@ LTO_DUMP_INSTALL_NAME := $(shell echo lto-dump|sed '$(program_transform_name)')
 # The LTO-specific object files inclued in $(LTO_EXE).
 LTO_OBJS = lto/lto-lang.o lto/lto.o lto/lto-object.o attribs.o lto/lto-partition.o lto/lto-symtab.o lto/lto-common.o
 lto_OBJS = $(LTO_OBJS)
+lto_FDAS = lto1.fda
 LTO_DUMP_OBJS = lto/lto-lang.o lto/lto-object.o attribs.o lto/lto-partition.o lto/lto-symtab.o lto/lto-dump.o lto/lto-common.o
 lto_dump_OBJS = $(LTO_DUMP_OBJS)
 
-# this is only useful in a LTO bootstrap, but this does not work right
-# now. Should reenable after this is fixed, but only when LTO bootstrap
-# is enabled.
-
-#ifeq ($(if $(wildcard ../stage_current),$(shell cat \
-#  ../stage_current)),stageautofeedback)
-#$(LTO_OBJS): CFLAGS += -fauto-profile=lto1.fda
-#$(LTO_OBJS): lto1.fda
-#endif
+ifeq ($(if $(wildcard ../stage_current),$(shell cat \
+  ../stage_current)),stageautofeedback)
+$(LTO_OBJS): CFLAGS += -fauto-profile=lto1.fda
+$(LTO_OBJS): lto1.fda
+endif
 
 # Rules
 
@@ -109,26 +106,32 @@ components_in_prev = "bfd opcodes binutils fixincludes gas gcc gmp mpfr mpc isl 
 components_in_prev_target = "libstdc++-v3 libsanitizer libvtv libgcc libbacktrace libphobos zlib libgomp libatomic"
 
 lto1.fda: create_fdas_for_lto1
-	$(PROFILE_MERGER) $(shell ls -ha lto1_*.fda) --output_file lto1.fda -gcov_version 2
+	$(PROFILE_MERGER) $(shell ls -ha lto1_*.fda) --output_file lto1.fda -gcov_version `../stage1-gcc/xgcc$(exeext) --print-autofdo-gcov-version`
 
 create_fdas_for_lto1: ../stage1-gcc/lto1$(exeext) ../prev-gcc/$(PERF_DATA)
 	for component_in_prev in "$(components_in_prev)"; do \
 	  perf_path=../prev-$$component_in_prev/$(PERF_DATA); \
-	  echo "Perf path:"; \
-	  echo $$perf_path; \
+	  echo "Perf path:" $$perf_path "..." `[ -f $$perf_path ] && echo exists || echo does not exist`; \
 	  if [ -f $$perf_path ]; then \
 	    profile_name=lto1_$$component_in_prev.fda; \
-	    $(CREATE_GCOV) -binary ../stage1-gcc/lto1$(exeext) -gcov $$profile_name -profile $$perf_path -gcov_version 2; \
+	    if [ "x`$(PERF) buildid-list -i $$perf_path | grep '/lto1$$' && echo yes`" != "x" ]; then \
+	      $(CREATE_GCOV) -binary ../stage1-gcc/lto1$(exeext) -gcov $$profile_name -profile $$perf_path -profiler $(AFDO_PROFILER) -gcov_version `../stage1-gcc/xgcc$(exeext) --print-autofdo-gcov-version` || exit 1; \
+	    else \
+	      echo "  warning: $$perf_path is missing lto1!"; \
+	    fi; \
 	  fi; \
 	done;
 
 	for component_in_prev_target in "$(components_in_prev_target)"; do \
 	  perf_path=../prev-$(TARGET_SUBDIR)/$$component_in_prev_target/$(PERF_DATA); \
-	  echo "Perf path:"; \
-	  echo $$perf_path; \
+	  echo "Perf path:" $$perf_path "..." `[ -f $$perf_path ] && echo exists || echo does not exist`; \
 	  if [ -f $$perf_path ]; then \
 	    profile_name=lto1_$$component_in_prev_target.fda; \
-	    $(CREATE_GCOV) -binary ../prev-gcc/lto1$(exeext) -gcov $$profile_name -profile $$perf_path -gcov_version 2; \
+	    if [ "x`$(PERF) buildid-list -i $$perf_path | grep '/lto1$$' && echo yes`" != "x" ]; then \
+	      $(CREATE_GCOV) -binary ../prev-gcc/lto1$(exeext) -gcov $$profile_name -profile $$perf_path -profiler $(AFDO_PROFILER) -gcov_version `../prev-gcc/xgcc$(exeext) --print-autofdo-gcov-version` || exit 1; \
+	    else \
+	      echo "  warning: $$perf_path is missing lto1!"; \
+	    fi; \
 	  fi; \
 	done;
 
